---
apiVersion: v1
kind: Namespace
metadata:
  name: farmyard

---
apiVersion: v1
kind: Namespace
metadata:
  name: warmfield

---
apiVersion: v1
kind: Namespace
metadata:
  name: treefarm

---
apiVersion: v1
kind: Namespace
metadata:
  name: charmland

---
apiVersion: v1
kind: Namespace
metadata:
  name: alarmzone