---
apiVersion: v1
kind: Service
metadata:
  name: chicken-svc
  namespace: farmyard
spec:
  selector:
    app: chicken
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sheep-svc
  namespace: warmfield
spec:
  selector:
    app: sheep
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: cow-svc
  namespace: warmfield
spec:
  selector:
    app: cow
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: bee-svc
  namespace: treefarm
spec:
  selector:
    app: bee
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-svc
  namespace: charmland
spec:
  selector:
    app: rabbit
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
